### ISSUE TITLE
Bug Testing and General Feedback

### ISSUE THREAD

**Issue by TechnoMysterio** [MobiusFlip/CrimsonRevelations#2]
I just noticed this mod today (somehow it flew under my radar until now) and was interested in seeing what it had to offer, so I've done some testing and found a few oddities here and there that might help with the overall polish. Despite that though, it's a very simple but very effective mod, so good work!

- The recipe for the Crimson Banner doesn't work if you place the recipe on the right side of the Arcane Workbench. Left side works fine, however. Picture:
![2020-01-30_13 37 51](https://user-images.githubusercontent.com/5113920/73456213-6991a080-4369-11ea-8f8e-214ae6146385.png)

- Some Crimson Armour recipes have a similar problem to the one above. Crimson Cult Boots don't craft if recipe is in top half of the Arcane Workbench, Crimson Cult Helm doesn't work on bottom half of the Arcane Workbench, and the Crimson Cult Hood doesn't work in the bottom half of the Arcane Workbench. Here's the boots recipe as an example:
![2020-01-30_13 44 55](https://user-images.githubusercontent.com/5113920/73456432-c9884700-4369-11ea-98d6-b8003e271752.png)

- There's a few problems with the Ancient Tile recipe. First is that it also seems to have the same problem as above again, where it doesn't work if done in the bottom half of the table. Second is that since I'm helping out with Thaumic Augmentation development, I've noticed there's a small recipe conflict between the current WIP version of it and Crimson Revelations, since both add a recipe for four Ancient Stone in a square. This'll probably need some further thought or discussion, but it's not too serious at the moment, especially since that version of Augmentation is still very much in development. 

- Suggestion for Crimson Praetor Armour recipes: it might be worth increasing the essentia cost a bit, but I was using an Ancient Infusion Altar to craft them which does lower essentia costs when crafting.

And that's about all of the problems I can find. Aside from that, this mod is excellent, the writing is great and the recipes are very helpful, so it's a good simple way to get access to all of the content that Thaumcraft 6 didn't manage to add before its hiatus. Augmentation is planned to get some of that content actually, but implemented in a different way. I shan't go into too much detail though, spoilers and all that.

While I'm here, I'll send you an invite to the Thaumcraft Addon Discord, it's a good place to discuss addon development or just about anything else really, so feel free to join if you want: https://discord.gg/bBsBJWW

**Comment by MobiusFlip** [comment]
Recipes are fixed and Praetor Armor costs are increased. Ancient Tile recipe was left as four Ancient Stone in a square, but I'd be willing to change it once that version of Thaumic Augmentation is out.
